import os
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# Set Page Architecture Configuration
st.set_page_config(
    page_title="BHMS Structural Fatigue Dashboard",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Application Custom Layout Header Branding
st.markdown("<h1 style='text-align: center; color: #1E3A8A;'>🏗️ Bridge & Structural Health Monitoring System</h1>", unsafe_allow_html=True)
st.markdown("<h3 style='text-align: center; color: #4B5563; margin-bottom: 30px;'>Structural Fatigue Life & Dynamic Load Monitoring Dashboard</h3>", unsafe_allow_html=True)

# File Paths (Generated by your fatigue_analyser.py core script)
STRAIN_DATA_FILE = "Corrected_Strain_Data.xlsx"
FATIGUE_DATA_FILE = "Rainflow_Fatigue_Results.xlsx"

# -------------------------------------------------------------
# SIDEBAR CONTROL DECK
# -------------------------------------------------------------
st.sidebar.markdown("## ⚙️ Dashboard Controls")
st.sidebar.info("Ensure you have run `python fatigue_analyser.py` first to generate the calculation engine files.")

if st.sidebar.button("🔄 Refresh Analysis Data"):
    st.rerun()

# Check for existence of backend execution files
if not os.path.exists(STRAIN_DATA_FILE) or not os.path.exists(FATIGUE_DATA_FILE):
    st.error(f"❌ Target Data Files Not Found! Please run your `fatigue_analyser.py` script first in this directory to generate: `{STRAIN_DATA_FILE}` and `{FATIGUE_DATA_FILE}`.")
else:
    # Load backend calculated structures
    @st.cache_data
    def load_dashboard_data():
        strain_df = pd.read_excel(STRAIN_DATA_FILE)
        strain_df['Datetime'] = pd.to_datetime(strain_df['Datetime'])
        
        # Load Fatigue parameters
        summary_df = pd.read_excel(FATIGUE_DATA_FILE, sheet_name='Summary_Dashboard')
        # Handle case where spectra might be empty notice or true dataframe
        try:
            spectra_df = pd.read_excel(FATIGUE_DATA_FILE, sheet_name='Rainflow_Spectra')
        except Exception:
            spectra_df = pd.DataFrame()
            
        return strain_df, summary_df, spectra_df

    df, summary, spectra = load_dashboard_data()

    # Extract Key Summary KPI Parameters out of parsed dataframe rows
    summary_dict = dict(zip(summary['Parameter Label'], summary['Value']))
    
    cat_num = summary_dict.get('Selected Structural Category Number', 'N/A')
    threshold = summary_dict.get('Active Fatigue Limit Threshold (MPa)', 'N/A')
    cycles_pass = summary_dict.get('Cycles Surpassing Threshold', 0)
    cycles_fail = summary_dict.get('Cycles Blocked Below Threshold', 0)
    damage_index = summary_dict.get('Cumulative Damage Index Factor (D)', 0.0)
    rul_hours = summary_dict.get('Estimated Remaining Life (Hours)', 'Infinite')
    rul_days = summary_dict.get('Estimated Remaining Life (Days)', 'Infinite')

    # -------------------------------------------------------------
    # KPI SCORECARD DASHBOARD LAYOUT
    # -------------------------------------------------------------
    st.markdown("---")
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric(
            label="Structural Eurocode Category", 
            value=f"FAT-Class {cat_num}", 
            delta=f"Limit: {threshold} MPa", 
            delta_color="inverse"
        )
        
    with col2:
        # Display Damage Index using scientific formatting notation if very small
        if isinstance(damage_index, float) and damage_index > 0:
            val_str = f"{damage_index:.2e}" if damage_index < 0.001 else f"{damage_index:.5f}"
        else:
            val_str = str(damage_index)
        st.metric(label="Cumulative Damage Index (D)", value=val_str)
        
    with col3:
        st.metric(
            label="Estimated Remaining Useful Life", 
            value=f"{rul_days} Days", 
            delta=f"{rul_hours} Hours Remaining"
        )
        
    with col4:
        st.metric(label="Valid Fatigue Load Cycles Counted", value=int(cycles_pass))

    # -------------------------------------------------------------
    # MAIN GRAPH ACTION: COMPREHENSIVE INTERACTIVE TIME-HISTORY
    # -------------------------------------------------------------
    st.markdown("### 📈 Time-History Dynamic Working Load Stress Graph")
    st.markdown("_Use the mouse wheel to zoom or drag boxes over target windows to analyze localized peak events._")
    
    # Render zoomable interactive plotly graph object
    fig = go.Figure()
    
    # Primary Dynamic Stress Plot
    fig.add_trace(go.Scatter(
        x=df['Datetime'],
        y=df['LiveLoad'],
        mode='lines',
        name='Live Dynamic Stress (MPa)',
        line=dict(color='#2563EB', width=1.5),
        opacity=0.85
    ))
    
    # Layout and design properties configuration
    fig.update_layout(
        xaxis_title="Measurement Timeline",
        yaxis_title="Calculated Stress (MPa)",
        hovermode="x unified",
        margin=dict(l=40, r=40, t=20, b=40),
        height=500,
        template="plotly_white",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    
    st.plotly_chart(fig, use_container_width=True)

    # -------------------------------------------------------------
    # LOWER SPECTRUM BREAKDOWN DETAILS
    # -------------------------------------------------------------
    st.markdown("---")
    left_col, right_col = st.columns(2)
    
    with left_col:
        st.markdown("### 📋 Dynamic Process Filtering Inspection Ledger")
        st.markdown("Verify data stream cleanliness across your 13 template pipeline columns:")
        
        # Display small interactive sample frame for visual data exploration
        st.dataframe(df.head(100), height=300, use_container_width=True)
        st.caption("Showing the first 100 historical intervals. Column sequence aligns to your exact layout template definition.")
        
    with right_col:
        st.markdown("### 📊 Rainflow Cycle Range Spectra")
        st.markdown("Distribution of recorded stress cycle counts passing your Category limits:")
        
        if not spectra.empty and 'Stress_Range_MPa' in spectra.columns:
            # Render a histogram mapping out the cycle load levels
            fig_hist = go.Figure()
            fig_hist.add_trace(go.Histogram(
                x=spectra['Goodman_Corrected_Range_MPa'],
                nbinsx=20,
                marker_color='#DC2626',
                opacity=0.75
            ))
            fig_hist.update_layout(
                xaxis_title="Goodman Corrected Range Amplitude (MPa)",
                yaxis_title="Count Concentration",
                margin=dict(l=40, r=40, t=20, b=40),
                height=300,
                template="plotly_white"
            )
            st.plotly_chart(fig_hist, use_container_width=True)
        else:
            st.warning("No recorded cycles managed to surpass your active Category Stress Threshold limit during this window.")